'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { parseCase, serializeCase } from '@/lib/jobmatch/case-file';
import {
  FACTORS,
  FACTOR_COLOR,
  FACTOR_NAME,
  PRESETS,
  answerFor,
  assessJob,
  buildReportHtml,
  clamp,
  compute,
  emptyAnswer,
  initialState,
  jobFullText,
  questionsFor,
  suggestFromText,
  type JobAssessment,
  type Question,
  type ToolState,
} from '@/lib/jobmatch/model';
import { OTHER_DISC, isMasterDisc, parseDisc, readPdfText } from '@/lib/jobmatch/pdf';

import { saveCaseAction } from '../actions';

interface StatusLine {
  text: string;
  kind: '' | 'busy' | 'ok' | 'bad';
}

const RAIL = [
  ['00', 'Introduktion'],
  ['01', 'Kandidat'],
  ['02', 'Kravprofil'],
  ['03', 'Vurdering'],
  ['04', 'Rapport'],
] as const;

const QUESTION_WEIGHTS = [
  { w: 0.5, label: 'Lav', title: 'Tæller halvt i din vurdering — punktet betyder mindre i netop denne stilling' },
  { w: 1, label: 'Normal', title: 'Tæller fuldt med i din vurdering' },
  { w: 1.6, label: 'Høj', title: 'Tæller 1,6 gange — punktet er særligt vigtigt for stillingen' },
  {
    w: 2.4,
    label: 'Kritisk',
    title:
      'Tæller 2,4 gange — og en score på 5 eller derunder udløser et forbehold i rapporten uanset totalen',
  },
] as const;

const FACTOR_WEIGHTS = [
  { w: 0.5, label: 'Lav' },
  { w: 1, label: 'Normal' },
  { w: 2, label: 'Høj' },
] as const;

const QUESTIONS_PER_PAGE = 3;

function danishToday(): string {
  return new Date().toLocaleDateString('da-DK', { day: 'numeric', month: 'long', year: 'numeric' });
}

function scaleClass(score: number | null): string {
  if (score === null) return 'scale';
  if (score <= 3) return 'scale lo';
  if (score <= 5) return 'scale mid';
  if (score <= 7) return 'scale lg';
  return 'scale hi';
}

/**
 * MasterDISC JobMatch — ported from public_html/jobmatch/vaerktoej.php.
 *
 * Same five steps, same texts, same calculation. What changed: the state lives
 * in React instead of a module-level object, the archive save goes through a
 * server action instead of arkiv.php, and the report is generated by
 * lib/jobmatch/model.ts. The report is still an HTML string that gets
 * A4-paginated by measuring the rendered blocks, because that is what makes the
 * print layout work.
 */
export function Tool() {
  const [state, setState] = useState<ToolState>(() => initialState(''));
  const [step, setStep] = useState(0);
  const [reportHtml, setReportHtml] = useState('');
  const [wide, setWide] = useState(true);
  const [termsWarn, setTermsWarn] = useState(false);
  const [showReject, setShowReject] = useState(false);
  const [discStatus, setDiscStatus] = useState<StatusLine>({ text: 'Ingen fil valgt', kind: '' });
  const [jobStatus, setJobStatus] = useState<StatusLine>({ text: 'Ingen fil valgt', kind: '' });
  const [jobPeek, setJobPeek] = useState<string | null>(null);
  const [jd, setJd] = useState<{ at: string; withExtra: boolean; assessment: JobAssessment | null } | null>(
    null,
  );
  const [suggestOut, setSuggestOut] = useState('');
  const [famOut, setFamOut] = useState('');
  const [newQName, setNewQName] = useState('');
  const [saveLabel, setSaveLabel] = useState('Gem sag som fil');
  const [arkivLabel, setArkivLabel] = useState('Gem i arkivet');
  const [arkivBusy, setArkivBusy] = useState(false);
  const [arkivStatus, setArkivStatus] = useState<{ text: string; color: string }>({
    text: '',
    color: 'var(--ink-45)',
  });

  const discInput = useRef<HTMLInputElement>(null);
  const jobInput = useRef<HTMLInputElement>(null);
  const caseInput = useRef<HTMLInputElement>(null);
  const termsWarnRef = useRef<HTMLParagraphElement>(null);
  const reportRef = useRef<HTMLDivElement>(null);
  const jobExtraTouched = useRef(false);

  const questions = useMemo(() => questionsFor(state), [state]);

  // The date label is set on the client so server and client markup agree.
  useEffect(() => {
    setState((current) =>
      current.meta.date ? current : { ...current, meta: { ...current.meta, date: danishToday() } },
    );
  }, []);

  // POC: the A4 rhythm only applies on wide screens, and it is recalculated
  // 250 ms after a resize settles.
  useEffect(() => {
    const apply = () => setWide(window.innerWidth > 820);
    apply();
    let timer: ReturnType<typeof setTimeout>;
    const onResize = () => {
      clearTimeout(timer);
      timer = setTimeout(apply, 250);
    };
    window.addEventListener('resize', onResize);
    return () => {
      clearTimeout(timer);
      window.removeEventListener('resize', onResize);
    };
  }, []);

  const pages: Question[][] = useMemo(() => {
    if (!wide) return [questions];
    const out: Question[][] = [];
    for (let i = 0; i < questions.length; i += QUESTIONS_PER_PAGE) {
      out.push(questions.slice(i, i + QUESTIONS_PER_PAGE));
    }
    return out.length ? out : [[]];
  }, [questions, wide]);

  // POC: the first question page is page 4, the report follows the last one.
  const reportPageNumber = 4 + pages.length;

  const buildReport = useCallback(() => {
    if (!state.terms.accepted) {
      setStep(0);
      setTermsWarn(true);
      return;
    }
    if (state.discRejected) {
      setStep(1);
      setShowReject(true);
      return;
    }
    setReportHtml(buildReportHtml(state, questions, reportPageNumber));
    setStep(4);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [questions, reportPageNumber, state]);

  const go = useCallback(
    (target: number) => {
      let next = target;
      if (!state.terms.accepted && next > 0) {
        next = 0;
        setTermsWarn(true);
        requestAnimationFrame(() =>
          termsWarnRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }),
        );
      }
      if (state.discRejected && next > 1) {
        next = 1;
        setShowReject(true);
      }
      if (next === 4) {
        buildReport();
        return;
      }
      setStep(next);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    },
    [buildReport, state.discRejected, state.terms.accepted],
  );

  /** packReport() from the POC: cut the report into A4 sheets by measuring. */
  useEffect(() => {
    const container = reportRef.current;
    if (!container || !reportHtml || step !== 4) return;

    const stage = document.createElement('div');
    stage.innerHTML = reportHtml;
    // The built-in end footer is dropped — each sheet gets its own.
    const blocks = Array.from(stage.children).filter(
      (child) => !child.classList.contains('repfoot'),
    );

    container.innerHTML = '';
    const makeSheet = (first: boolean, num: number) => {
      const sheet = document.createElement('div');
      sheet.className = 'rpage';
      sheet.innerHTML =
        (first ? '' : '<div class="page-head"><b>MasterDISC - Jobmatch</b></div>') +
        '<div class="rbody"></div>' +
        `<div class="repfoot"><span>MasterDISC · Jobmatch · Fortroligt</span><span class="pgnum">${num}</span></div>`;
      return sheet;
    };

    let num = reportPageNumber;
    const firstSheet = makeSheet(true, num);
    container.appendChild(firstSheet);
    const firstBody = firstSheet.querySelector('.rbody');
    if (!firstBody) return;
    for (const block of blocks) firstBody.appendChild(block);

    if (window.innerWidth > 820) {
      const sheets = [firstSheet];
      let guard = 0;
      while (guard < 25) {
        guard += 1;
        const sheet = sheets[sheets.length - 1];
        if (!sheet) break;
        const body = sheet.querySelector('.rbody');
        if (!body) break;
        const limit = (sheet.offsetWidth * 297) / 210 - 110; /* plads til den navy fod */
        const top = sheet.getBoundingClientRect().top;
        const children = Array.from(body.children);
        let cut = -1;
        for (let i = 0; i < children.length; i += 1) {
          const child = children[i];
          if (child && child.getBoundingClientRect().bottom - top > limit && i > 0) {
            cut = i;
            break;
          }
        }
        if (cut === -1) break;
        num += 1;
        const nextSheet = makeSheet(false, num);
        container.appendChild(nextSheet);
        const nextBody = nextSheet.querySelector('.rbody');
        if (!nextBody) break;
        for (const child of children.slice(cut)) nextBody.appendChild(child);
        sheets.push(nextSheet);
      }
    }
  }, [reportHtml, reportPageNumber, step, wide]);

  // ------------------------------------------------------------------ helpers

  const setMeta = (key: keyof ToolState['meta'], value: string) =>
    setState((current) => ({ ...current, meta: { ...current.meta, [key]: value } }));

  const setAnswer = (id: string, patch: Partial<ReturnType<typeof emptyAnswer>>) =>
    setState((current) => ({
      ...current,
      answers: { ...current.answers, [id]: { ...answerFor(current, id), ...patch } },
    }));

  const refreshJd = useCallback(() => {
    const at = new Date().toLocaleTimeString('da-DK', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
    const full = jobFullText(state);
    setJd({
      at,
      withExtra: Boolean(state.jobExtra),
      assessment: full ? assessJob(full) : null,
    });
  }, [state]);

  // POC: the assessment refreshes itself shortly after you stop typing.
  useEffect(() => {
    if (!jobExtraTouched.current) return;
    const timer = setTimeout(() => refreshJd(), 600);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state.jobExtra]);

  async function handleDiscFile(file: File) {
    setDiscStatus({ text: `Læser ${file.name} …`, kind: 'busy' });
    try {
      const text = await readPdfText(file);
      if (!isMasterDisc(text)) {
        setState((current) => ({ ...current, discRejected: true, discFile: '' }));
        const other = text.match(OTHER_DISC);
        setShowReject(true);
        setDiscStatus({
          kind: 'bad',
          text: `✕ Afvist: ${file.name} er ikke en MasterDISC-profil${
            other?.[1] ? ` — den ligner ${other[1]}` : ''
          }.`,
        });
        return;
      }
      const parsed = parseDisc(text);
      setShowReject(false);
      setState((current) => ({
        ...current,
        discRejected: false,
        discFile: file.name,
        work: parsed.work ?? current.work,
        meta:
          parsed.name && !current.meta.cand
            ? { ...current.meta, cand: parsed.name }
            : current.meta,
      }));
      if (parsed.work) {
        setDiscStatus({
          kind: 'ok',
          text: `✓ ${file.name} — MasterDISC-profil godkendt, arbejdsprofilen indlæst. Tjek tallene nedenfor.`,
        });
      } else {
        setDiscStatus({
          kind: 'bad',
          text: `! MasterDISC-profil genkendt, men tallene kunne ikke aflæses i ${file.name}. Indtast dem manuelt.`,
        });
      }
    } catch {
      setDiscStatus({
        kind: 'bad',
        text: '! Filen kunne ikke læses automatisk. Indtast tallene manuelt nedenfor.',
      });
    }
  }

  async function handleJobFile(file: File) {
    setJobStatus({ text: `Læser ${file.name} …`, kind: 'busy' });
    try {
      const text =
        file.type === 'application/pdf' || /\.pdf$/i.test(file.name)
          ? await readPdfText(file)
          : await file.text();

      let role: string | null = null;
      const titleMatch = text.match(/Titel:\s*(.{2,80})/);
      if (titleMatch?.[1]) {
        let candidate = titleMatch[1].split(/\n/)[0] ?? '';
        /* klip ved naeste sektionsoverskrift, hvis PDF-teksten er loebet sammen */
        candidate =
          candidate.split(
            /\s+(?=(?:Formål|Ansvar|Arbejdsopgaver|Arbejdsområder|Succeskriterier|Faglige|Personlige|Organisatoriske|Kvalifikationer|Reference(?:r)?|Løn|Om\s|KPI|Mødedeltagelse|Stillingen)\b)/i,
          )[0] ?? '';
        candidate = candidate.replace(/[.,;:·•\-–]+\s*$/, '').trim();
        if (candidate.length > 50) candidate = candidate.slice(0, 50).replace(/\s+\S*$/, '').trim();
        if (candidate) role = candidate;
      }

      setState((current) => ({
        ...current,
        jobFile: file.name,
        jobText: text,
        meta: role && !current.meta.role ? { ...current.meta, role } : current.meta,
      }));
      setJobPeek(text.slice(0, 4000));
      setJobStatus({
        kind: 'ok',
        text: `✓ ${file.name} — ${text.trim().split(/\s+/).length} ord indlæst.`,
      });
      const full = `${text}\n${state.jobExtra || ''}`.trim();
      setJd({
        at: new Date().toLocaleTimeString('da-DK', {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }),
        withExtra: Boolean(state.jobExtra),
        assessment: full ? assessJob(full) : null,
      });
    } catch {
      setState((current) => ({ ...current, jobFile: file.name }));
      setJobStatus({
        kind: 'bad',
        text: '! Filen kunne ikke læses. Prøv en tekstfil, eller sæt kravprofilen manuelt.',
      });
    }
  }

  function saveCaseToFile() {
    const blob = new Blob([serializeCase(state)], { type: 'application/json' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    const tag = state.meta.case || state.meta.cand || 'kandidat';
    link.download = `jobmatch-${tag.toLowerCase().replace(/[^a-z0-9æøå]+/gi, '-')}.json`;
    link.click();
    URL.revokeObjectURL(link.href);
    setSaveLabel('Sag gemt');
    setTimeout(() => setSaveLabel('Gem sag som fil'), 1800);
  }

  async function loadCaseFromFile(file: File) {
    try {
      const loaded = parseCase(await file.text());
      setState(loaded);
      setShowReject(loaded.discRejected);
      setReportHtml('');
      setDiscStatus({ kind: 'ok', text: `✓ Sag indlæst fra ${file.name}` });
      const full = jobFullText(loaded);
      if (full) {
        setJd({
          at: new Date().toLocaleTimeString('da-DK', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
          }),
          withExtra: Boolean(loaded.jobExtra),
          assessment: assessJob(full),
        });
      }
    } catch {
      window.alert('Filen kunne ikke læses som en gemt sag.');
    }
  }

  async function saveToArchive() {
    const kandidat = state.meta.cand.trim();
    if (!kandidat) {
      setArkivStatus({
        text: 'Udfyld kandidatens navn på trin 1, før sagen kan gemmes.',
        color: 'var(--stop)',
      });
      return;
    }
    setArkivBusy(true);
    setArkivLabel('Gemmer …');
    setArkivStatus({ text: 'Sender til serveren …', color: 'var(--ink-45)' });

    const parts: string[] = [];
    if (state.meta.comp) parts.push(state.meta.comp);
    if (state.meta.round) parts.push(state.meta.round);
    const total = compute(state, questions).total;
    if (Number.isFinite(total)) parts.push(`matchscore ${total}`);

    const result = await saveCaseAction({
      navn: kandidat,
      stilling: state.meta.role.trim(),
      dato: state.meta.date,
      note: parts.join(' · '),
      caseJson: serializeCase(state),
    });

    if (result.ok) {
      setArkivLabel('Gemt i arkivet');
      setArkivStatus({
        text: 'Sagen er gemt. Vil du også arkivere selve rapporten, så tryk "Udskriv eller gem som PDF", gem den som PDF, og læg den ind under Jobmatchfiler.',
        color: 'var(--ok)',
      });
      setTimeout(() => {
        setArkivLabel('Gem i arkivet');
        setArkivBusy(false);
      }, 2600);
      return;
    }
    setArkivLabel('Gem i arkivet');
    setArkivBusy(false);
    setArkivStatus({ text: `Kunne ikke gemme: ${result.fejl}`, color: 'var(--stop)' });
  }

  function generateCaseNumber() {
    const currentNumber = state.meta.case.match(/^(\d+)/);
    const next = currentNumber?.[1] ? Number(currentNumber[1]) + 1 : 1;
    const clean = (value: string) => value.trim().replace(/[^A-Za-zÆØÅæøå0-9]+/g, '');
    let tag =
      clean(state.meta.role) || clean(state.meta.comp) || clean(state.meta.cand) || 'Sag';
    tag = tag.charAt(0).toUpperCase() + tag.slice(1);
    setMeta('case', `${String(next).padStart(2, '0')}-${tag}`);
  }

  function addCustomQuestion() {
    const name = newQName.trim();
    if (!name) return;
    const def = { id: `c${Date.now()}`, t: name.charAt(0).toUpperCase() + name.slice(1) };
    setState((current) => ({
      ...current,
      customQ: [...current.customQ, def],
      answers: { ...current.answers, [def.id]: emptyAnswer() },
    }));
    setNewQName('');
  }

  function removeCustomQuestion(id: string) {
    setState((current) => {
      const answers = { ...current.answers };
      delete answers[id];
      return { ...current, customQ: current.customQ.filter((c) => c.id !== id), answers };
    });
  }

  const answeredCount = questions.filter((q) => answerFor(state, q.id).score !== null).length;
  const naCount = questions.filter((q) => answerFor(state, q.id).na).length;

  // -------------------------------------------------------------------- views

  const questionNode = (question: Question, index: number) => {
    const answer = answerFor(state, question.id);
    return (
      <div className={answer.na ? 'q off' : 'q'} id={`q_${question.id}`} key={question.id}>
        <div className="qhead">
          <div>
            <span className="qno">
              SPØRGSMÅL {String(index + 1).padStart(2, '0')}
              {question.custom ? ' · EGET' : ''}
            </span>
            <h3>{question.t}</h3>
          </div>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <div className="weights">
              {QUESTION_WEIGHTS.map((weight) => (
                <button
                  type="button"
                  key={weight.w}
                  title={weight.title}
                  className={answer.weight === weight.w ? 'on' : undefined}
                  onClick={() => setAnswer(question.id, { weight: weight.w })}
                >
                  {weight.label}
                </button>
              ))}
            </div>
            {question.custom ? (
              <button
                type="button"
                className="qdel"
                onClick={() => removeCustomQuestion(question.id)}
              >
                Fjern
              </button>
            ) : null}
          </div>
        </div>
        <p className="qd">{question.d}</p>
        <div className="scalewrap">
          <div className={scaleClass(answer.score)}>
            {Array.from({ length: 10 }, (_, i) => i + 1).map((value) => (
              <button
                type="button"
                key={value}
                className={answer.score === value ? 'on' : undefined}
                onClick={() => setAnswer(question.id, { score: value, na: false })}
              >
                {value}
              </button>
            ))}
          </div>
          <button
            type="button"
            className={answer.na ? 'na on' : 'na'}
            onClick={() =>
              setAnswer(question.id, { na: !answer.na, score: !answer.na ? null : answer.score })
            }
          >
            Ikke relevant
          </button>
          <button
            type="button"
            className="rst"
            title="Rydder score, ikke relevant og bemærkning på dette punkt"
            onClick={() => setAnswer(question.id, { score: null, na: false, note: '' })}
          >
            Nulstil svar
          </button>
          <button type="button" className="updm" onClick={() => buildReport()}>
            Opdater Jobmatch
          </button>
        </div>
        <div className="qguide">
          <span>
            <b>1</b>
            {question.g[1]}
          </span>
          <span>
            <b>5</b>
            {question.g[5]}
          </span>
          <span>
            <b>10</b>
            {question.g[10]}
          </span>
        </div>
        <div className="note">
          <textarea
            placeholder="Bemærkning (kommer med i rapporten)"
            value={answer.note}
            onChange={(event) => setAnswer(question.id, { note: event.target.value })}
          />
        </div>
      </div>
    );
  };

  const questionTail = (
    <div className="qadd">
      <span className="sub" style={{ border: 0, padding: 0, margin: '0 0 10px', display: 'block' }}>
        Tilføj eget spørgsmål
      </span>
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <input
          type="text"
          placeholder="Fx Sprogegenskaber"
          style={{ flex: 1, minWidth: 200 }}
          value={newQName}
          onChange={(event) => setNewQName(event.target.value)}
        />
        <button type="button" className="btn ghost small" onClick={addCustomQuestion}>
          Tilføj spørgsmål
        </button>
      </div>
      <p style={{ fontSize: 12, color: 'var(--ink-45)', margin: '8px 0 18px' }}>
        Valgfrit punkt, der rates 1–10 som de øvrige — fx sprogegenskaber, kørekort eller
        systemkendskab. Det tæller med i din vurdering og kommer med i rapporten.
      </p>
      <span className="sub" style={{ border: 0, padding: 0, margin: '0 0 10px', display: 'block' }}>
        Vægtning af den samlede score
      </span>
      <input
        type="range"
        min={0}
        max={100}
        step={5}
        value={state.mix}
        style={{ width: '100%', accentColor: 'var(--ink)' }}
        onChange={(event) =>
          setState((current) => ({ ...current, mix: Number(event.target.value) }))
        }
      />
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          gap: 10,
          fontSize: 12,
          fontWeight: 700,
          color: 'var(--ink)',
          margin: '4px 0 6px',
        }}
      >
        <span>Din vurdering {state.mix} %</span>
        {state.mix === 60 ? (
          <span
            style={{
              border: '1px solid var(--gold)',
              color: 'var(--gold)',
              borderRadius: 100,
              padding: '2px 10px',
              fontSize: 9.5,
              letterSpacing: '.14em',
              textTransform: 'uppercase',
            }}
          >
            Standard
          </span>
        ) : (
          <span style={{ color: 'var(--ink-45)', fontWeight: 600, fontSize: 11 }}>
            (standard er 60/40)
          </span>
        )}
        <span>Rollematch {100 - state.mix} %</span>
      </div>
      <p style={{ fontSize: 13.5, lineHeight: 1.55, color: 'var(--ink-70)', margin: '2px 0 16px' }}>
        <strong style={{ color: 'var(--ink)' }}>Hvorfor er standarden 60/40?</strong> Din vurdering
        vejer 60 %, fordi den dækker det, der bedst forudsiger, om ansættelsen lykkes: teori,
        erfaring, referencer og motivation — altså om personen <em>kan og vil</em> jobbet.
        Rollematchet vejer 40 %, fordi DISC-profilen fortæller, <em>hvordan</em> personen vil
        arbejde — nok til at flytte scoren mærkbart, men aldrig nok til at afgøre beslutningen
        alene. Det er Coachers&apos; anbefaling — forstå vægtningen, før du ændrer den, og juster
        kun med en klar grund, fx stor erfaring med netop denne rolle.
      </p>
      <button type="button" className="updm" style={{ margin: '0 0 16px' }} onClick={() => buildReport()}>
        Opdater Jobmatch
      </button>
      <span style={{ fontSize: 11.5, fontWeight: 600, color: 'var(--ink-45)' }}>
        {answeredCount} besvaret · {naCount} ikke relevant ·{' '}
        {questions.length - answeredCount - naCount} mangler
      </span>
    </div>
  );

  return (
    <>
      <header className="md-head">
        <div className="shell headrow">
          <div>
            <h1 className="logo">
              <span className="dots">
                <i />
                <i />
                <i />
                <i />
              </span>
              <span className="wordmark">Master DISC</span>
            </h1>
            <div className="prodtitle">MasterDISC Jobmatch</div>
          </div>
          <div className="stamp">Fortroligt · må ikke videregives</div>
        </div>
      </header>
      <div className="md-gradient" />
      <div className="shell" style={{ paddingTop: 8 }}>
        <div className="layout">
          <nav className="rail" aria-label="Trin">
            <ol>
              {RAIL.map(([number, title], index) => (
                <li key={number} className={step === index ? 'on' : undefined}>
                  <button type="button" onClick={() => go(index)}>
                    <span className="n">{number}</span>
                    <span className="t">{title}</span>
                  </button>
                </li>
              ))}
            </ol>
            <p className="hint">
              Alt bliver i browseren. Intet sendes videre. Gem sagen som fil, hvis du vil arbejde
              videre senere.
            </p>
          </nav>

          <main>
            {/* ============ STEP 0 · INTRODUKTION ============ */}
            <section className={step === 0 ? 'step on' : 'step'} id="step0">
              <div className="page">
                <div className="page-body">
                  <div className="card">
                    <p className="eyebrow">Coachers · MasterDISC-familien</p>
                    <h2>Velkommen til JobMatch</h2>
                    <p className="lede">
                      JobMatch er tillægsproduktet til MasterDISC, når du skal ansætte. Værktøjet
                      holder kandidatens adfærdsprofil op mod den kravprofil, du sætter for
                      stillingen — og kombinerer det med din egen vurdering af alt det, en test
                      aldrig måler: kemi, faglighed, referencer og motivation. Resultatet er én
                      samlet matchscore og en rapport, der er klar til dialog med kandidaten og
                      resten af ansættelsesudvalget.
                    </p>

                    <div className="twocol" style={{ margin: '4px 0 6px' }}>
                      <div>
                        <div className="colh">
                          <i style={{ background: 'var(--S)' }} />
                          JobMatch er
                        </div>
                        <ul className="shortlist">
                          <li>
                            <i style={{ background: 'var(--S)' }} />
                            <span>
                              Struktur på ansættelsesbeslutningen — adfærd og ledervurdering samlet
                              ét sted
                            </span>
                          </li>
                          <li>
                            <i style={{ background: 'var(--S)' }} />
                            <span>Et fælles sprog mellem ansættende leder, HR og kandidat</span>
                          </li>
                          <li>
                            <i style={{ background: 'var(--S)' }} />
                            <span>
                              Et afsæt for anden samtale, referencetagning og onboarding
                            </span>
                          </li>
                        </ul>
                      </div>
                      <div>
                        <div className="colh">
                          <i style={{ background: 'var(--D)' }} />
                          JobMatch er ikke
                        </div>
                        <ul className="shortlist">
                          <li>
                            <i style={{ background: 'var(--D)' }} />
                            <span>
                              En måling af kompetencer — lav score betyder &quot;kræver bevidst
                              indsats&quot;, ikke &quot;kan ikke&quot;
                            </span>
                          </li>
                          <li>
                            <i style={{ background: 'var(--D)' }} />
                            <span>En dom over kandidaten eller en facitliste</span>
                          </li>
                          <li>
                            <i style={{ background: 'var(--D)' }} />
                            <span>En erstatning for samtalen — rapporten kvalificerer den</span>
                          </li>
                        </ul>
                      </div>
                    </div>

                    <p className="sub">Sådan arbejder du med værktøjet</p>
                    <div className="qgrid">
                      <article style={{ background: 'var(--white)' }}>
                        <div className="qn">01</div>
                        <span>
                          <strong style={{ color: 'var(--ink)' }}>Kandidat og stilling.</strong>{' '}
                          Upload kandidatens MasterDISC-profil og stillingsbeskrivelsen —
                          arbejdsprofilens tal læses automatisk.
                        </span>
                      </article>
                      <article style={{ background: 'var(--white)' }}>
                        <div className="qn">02</div>
                        <span>
                          <strong style={{ color: 'var(--ink)' }}>Kravprofil.</strong> Fastlæg
                          hvilken adfærd rollen kalder på, sæt spændet — og vægt de DISC-faktorer,
                          der er vigtigst at ramme.
                        </span>
                      </article>
                      <article style={{ background: 'var(--white)' }}>
                        <div className="qn">03</div>
                        <span>
                          <strong style={{ color: 'var(--ink)' }}>Din vurdering.</strong> Scor kemi,
                          faglighed, motivation og andre områder fra 1 til 10. Sæt &quot;ikke
                          relevant&quot;, hvor spørgsmålet ikke giver mening.
                        </span>
                      </article>
                      <article style={{ background: 'var(--white)' }}>
                        <div className="qn">04</div>
                        <span>
                          <strong style={{ color: 'var(--ink)' }}>Rapport.</strong> Få den samlede
                          matchscore med intervalguide, en begrundet anbefaling og spørgsmål til
                          næste samtale.
                        </span>
                      </article>
                    </div>

                    <p className="sub">MasterDISC-familien</p>
                    <div className="chips" style={{ marginBottom: 4 }}>
                      <span
                        className="chip"
                        style={{
                          cursor: 'default',
                          background: 'var(--white)',
                          border: '2px solid var(--gold)',
                          fontWeight: 700,
                          color: 'var(--ink)',
                        }}
                      >
                        JobMatch
                      </span>
                      {['Basisprofil', 'Jobprofil', 'Teamprofil'].map((product) => (
                        <button
                          type="button"
                          className="chip"
                          key={product}
                          onClick={() =>
                            setFamOut(`Kontakt Coachers for dine muligheder for en ${product}.`)
                          }
                        >
                          {product}
                        </button>
                      ))}
                    </div>
                    <p
                      style={{
                        fontSize: 13,
                        fontWeight: 600,
                        color: 'var(--gold)',
                        margin: '2px 0 0',
                        minHeight: 20,
                      }}
                      aria-live="polite"
                    >
                      {famOut}
                    </p>

                    <div className="disclaim" style={{ margin: '20px 0 0' }}>
                      <b>Forbehold</b>
                      JobMatch-rapporten er et afsæt for dialog samt et støtteværktøj i din
                      beslutning. Den måler ikke værdier, kompetencer og integritet, så den må
                      aldrig stå alene og garanterer aldrig et sikkert match. Husk, at beslutningen
                      altid er din egen.
                    </div>

                    <p className="sub">Vilkår for brug</p>
                    <div className="jdpanel" style={{ marginTop: 0 }}>
                      <ul className="shortlist" style={{ fontSize: 13 }}>
                        <li>
                          <i style={{ background: 'var(--gold)' }} />
                          <span>
                            JobMatch er et støtte- og hjælpeværktøj. Værktøjet alene må aldrig
                            træffe en ansættelsesbeslutning.
                          </span>
                        </li>
                        <li>
                          <i style={{ background: 'var(--gold)' }} />
                          <span>
                            Ansvaret for enhver vurdering og beslutning hviler alene på den leder,
                            der rekrutterer — og på dennes virksomhed.
                          </span>
                        </li>
                        <li>
                          <i style={{ background: 'var(--gold)' }} />
                          <span>
                            Coachers fraskriver sig ethvert ansvar for beslutninger, vurderinger og
                            handlinger truffet på baggrund af værktøjet og dets rapporter.
                          </span>
                        </li>
                        <li>
                          <i style={{ background: 'var(--gold)' }} />
                          <span>
                            Du er ansvarlig for, at brugen sker i overensstemmelse med gældende
                            lovgivning, herunder håndtering af kandidatens oplysninger — og for at
                            kandidaten er informeret.
                          </span>
                        </li>
                        <li>
                          <i style={{ background: 'var(--gold)' }} />
                          <span>
                            Rapporter og sager er fortrolige og må ikke videregives uden samtykke.
                          </span>
                        </li>
                      </ul>
                      <label
                        style={{
                          display: 'flex',
                          gap: 11,
                          alignItems: 'flex-start',
                          marginTop: 14,
                          cursor: 'pointer',
                          fontSize: 13.5,
                          fontWeight: 600,
                          color: 'var(--ink)',
                        }}
                      >
                        <input
                          type="checkbox"
                          style={{
                            width: 18,
                            height: 18,
                            marginTop: 2,
                            accentColor: 'var(--ink)',
                            flexShrink: 0,
                          }}
                          checked={state.terms.accepted}
                          onChange={(event) => {
                            const accepted = event.target.checked;
                            setState((current) => ({
                              ...current,
                              terms: {
                                accepted,
                                when: accepted ? new Date().toLocaleDateString('da-DK') : '',
                              },
                            }));
                            if (accepted) setTermsWarn(false);
                          }}
                        />
                        <span>
                          Jeg bekræfter, at JobMatch alene er et støtte- og hjælpeværktøj, at
                          værktøjet ikke alene må træffe ansættelsesbeslutningen, og at ansvaret
                          alene hviler på mig som rekrutterende leder. Jeg har læst og accepterer
                          vilkårene. Accepten registreres med dato i sagen og i rapporten.
                        </span>
                      </label>
                      <p
                        ref={termsWarnRef}
                        hidden={!termsWarn}
                        style={{
                          margin: '10px 0 0',
                          fontSize: 12.5,
                          fontWeight: 700,
                          color: 'var(--stop)',
                        }}
                      >
                        Du skal acceptere vilkårene, før du kan fortsætte.
                      </p>
                    </div>

                    <div className="actions" style={{ marginTop: 24 }}>
                      <button
                        type="button"
                        className="btn ghost"
                        onClick={() => caseInput.current?.click()}
                      >
                        Åbn gemt sag
                      </button>
                    </div>
                  </div>
                </div>
                <div className="pager noprint">
                  <span />
                  <button type="button" className="btn" onClick={() => go(1)}>
                    Næste side
                  </button>
                </div>
                <div className="page-foot">
                  <span>MasterDISC · Jobmatch · Fortroligt</span>
                  <span className="pgnum">1</span>
                </div>
              </div>
            </section>

            {/* ============ STEP 1 ============ */}
            <section className={step === 1 ? 'step on' : 'step'} id="step1">
              <div className="page">
                <div className="page-head">
                  <b>MasterDISC - Jobmatch</b>
                </div>
                <div className="page-body">
                  <div className="card">
                    <p className="eyebrow">Trin 01</p>
                    <h2>Kandidat og stilling</h2>
                    <p className="lede">
                      Læg kandidatens MasterDISC-profil og stillingsbeskrivelsen ind. Værktøjet
                      forsøger at læse DISC-tallene automatisk — tjek dem altid efter, og ret dem,
                      hvis noget ser forkert ud.
                    </p>

                    <div className="grid2">
                      <button
                        type="button"
                        className="drop"
                        onClick={() => discInput.current?.click()}
                        onDragEnter={(event) => event.preventDefault()}
                        onDragOver={(event) => event.preventDefault()}
                        onDrop={(event) => {
                          event.preventDefault();
                          const file = event.dataTransfer.files[0];
                          if (file) void handleDiscFile(file);
                        }}
                      >
                        <b>MasterDISC-profil</b>
                        <small>
                          PDF fra rapportgeneratoren. Arbejdsprofilens tal (graf 1) hentes
                          automatisk.
                        </small>
                        <span className={discStatus.kind ? `status ${discStatus.kind}` : 'status'}>
                          {discStatus.text}
                        </span>
                      </button>
                      <button
                        type="button"
                        className="drop"
                        onClick={() => jobInput.current?.click()}
                        onDragEnter={(event) => event.preventDefault()}
                        onDragOver={(event) => event.preventDefault()}
                        onDrop={(event) => {
                          event.preventDefault();
                          const file = event.dataTransfer.files[0];
                          if (file) void handleJobFile(file);
                        }}
                      >
                        <b>Stillingsbeskrivelse</b>
                        <small>
                          PDF eller tekstfil. Bruges til at foreslå en kravprofil på næste trin.
                        </small>
                        <span className={jobStatus.kind ? `status ${jobStatus.kind}` : 'status'}>
                          {jobStatus.text}
                        </span>
                      </button>
                    </div>

                    <div
                      hidden={!showReject}
                      style={{
                        marginTop: 14,
                        background: '#F9E9E7',
                        border: '1.5px solid var(--D)',
                        borderRadius: 10,
                        padding: '14px 16px',
                        fontSize: 13.5,
                        lineHeight: 1.5,
                        color: 'var(--stop)',
                      }}
                    >
                      <b
                        style={{
                          display: 'block',
                          fontSize: 9.5,
                          fontWeight: 700,
                          letterSpacing: '.18em',
                          textTransform: 'uppercase',
                          marginBottom: 5,
                        }}
                      >
                        Opgaven er afvist
                      </b>
                      Den uploadede profil er ikke en MasterDISC-rapport. JobMatch er bygget til
                      MasterDISC og kan kun bruges med en original MasterDISC-rapport fra Coachers —
                      hele opgaven er derfor afvist, og du kan ikke fortsætte, før en gyldig
                      MasterDISC-profil er lagt ind. Kontakt Coachers for en MasterDISC-basisprofil.
                    </div>

                    <input
                      type="file"
                      ref={discInput}
                      accept=".pdf"
                      hidden
                      onChange={(event) => {
                        const file = event.target.files?.[0];
                        if (file) void handleDiscFile(file);
                      }}
                    />
                    <input
                      type="file"
                      ref={jobInput}
                      accept=".pdf,.txt,.md"
                      hidden
                      onChange={(event) => {
                        const file = event.target.files?.[0];
                        if (file) void handleJobFile(file);
                      }}
                    />
                    <input
                      type="file"
                      ref={caseInput}
                      accept=".json"
                      hidden
                      onChange={(event) => {
                        const file = event.target.files?.[0];
                        if (file) void loadCaseFromFile(file);
                        event.target.value = '';
                      }}
                    />

                    {jobPeek !== null ? (
                      <details className="filepeek">
                        <summary>Læst tekst fra stillingsbeskrivelsen</summary>
                        <pre>{jobPeek}</pre>
                      </details>
                    ) : null}

                    {jd ? (
                      <div className="jdpanel">
                        <div
                          style={{
                            display: 'flex',
                            justifyContent: 'space-between',
                            alignItems: 'center',
                            gap: 12,
                            flexWrap: 'wrap',
                            marginBottom: 12,
                          }}
                        >
                          <span className="sub" style={{ margin: 0, padding: 0, border: 0 }}>
                            Vurdering af stillingsbeskrivelsen
                          </span>
                          <button type="button" className="btn ghost small" onClick={refreshJd}>
                            Opdater vurdering
                          </button>
                        </div>
                        <div>
                          {jd.assessment ? (
                            <>
                              <p
                                style={{
                                  margin: '0 0 8px',
                                  fontSize: 10.5,
                                  fontWeight: 700,
                                  letterSpacing: '.14em',
                                  textTransform: 'uppercase',
                                  color: 'var(--ink-45)',
                                }}
                              >
                                Vurdering opdateret kl. {jd.at} ·{' '}
                                {jd.withExtra
                                  ? 'inkl. supplerende beskrivelse'
                                  : 'stillingsbeskrivelsen alene'}
                              </p>
                              <div className="jdhead">
                                <span className="jdlvl" style={{ background: jd.assessment.col }}>
                                  {jd.assessment.level}
                                </span>
                                <p>{jd.assessment.head}</p>
                              </div>
                              <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--ink-70)' }}>
                                {jd.assessment.disc}
                              </p>
                              <div className="twocol">
                                {jd.assessment.found.length ? (
                                  <div>
                                    <div className="colh" style={{ fontSize: 13 }}>
                                      <i style={{ background: 'var(--ok)' }} />
                                      Det er på plads
                                    </div>
                                    <ul className="shortlist" style={{ fontSize: 12.5 }}>
                                      {jd.assessment.found.slice(0, 5).map((check) => (
                                        <li key={check.id}>
                                          <i style={{ background: 'var(--ok)' }} />
                                          <span>{check.ok}</span>
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                ) : null}
                                {jd.assessment.missing.length ? (
                                  <div>
                                    <div className="colh" style={{ fontSize: 13 }}>
                                      <i style={{ background: 'var(--stop)' }} />
                                      Kunne beskrives yderligere
                                    </div>
                                    <ul className="shortlist" style={{ fontSize: 12.5 }}>
                                      {jd.assessment.missing.slice(0, 5).map((check) => (
                                        <li key={check.id}>
                                          <i style={{ background: 'var(--stop)' }} />
                                          <span>{check.miss}</span>
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                ) : (
                                  <div>
                                    <div className="colh" style={{ fontSize: 13 }}>
                                      <i style={{ background: 'var(--ok)' }} />
                                      Ingen mangler fundet
                                    </div>
                                  </div>
                                )}
                              </div>
                            </>
                          ) : (
                            <p style={{ margin: 0, fontSize: 13, color: 'var(--ink-45)' }}>
                              Læg en stillingsbeskrivelse ind ovenfor — eller skriv en supplerende
                              beskrivelse nedenfor — og tryk &quot;Opdater vurdering&quot;.
                            </p>
                          )}
                        </div>
                      </div>
                    ) : null}

                    <p className="sub">Supplerende beskrivelse (valgfrit)</p>
                    <textarea
                      rows={4}
                      placeholder="Skriv det, der ikke står i stillingsbeskrivelsen — fx de røde punkter fra vurderingen ovenfor: succeskriterier og KPI'er, organisering og team, vilkår, udviklingsmuligheder …"
                      value={state.jobExtra}
                      onChange={(event) => {
                        jobExtraTouched.current = true;
                        setState((current) => ({ ...current, jobExtra: event.target.value }));
                      }}
                    />
                    <p
                      style={{
                        fontSize: 12,
                        color: 'var(--ink-45)',
                        margin: '6px 0 0',
                        maxWidth: '70ch',
                      }}
                    >
                      Teksten tæller med på lige fod med stillingsbeskrivelsen — både i
                      kvalitetsvurderingen ovenfor og i forslaget til kravprofilen på næste side.
                      Tryk &quot;Opdater vurdering&quot;, når du har skrevet.
                    </p>

                    <p className="sub" style={{ marginTop: 26 }}>
                      Sagens stamdata
                    </p>
                    <div className="grid3">
                      <label className="f">
                        <span>Kandidat</span>
                        <input
                          type="text"
                          placeholder="Fulde navn"
                          value={state.meta.cand}
                          onChange={(event) => setMeta('cand', event.target.value)}
                        />
                      </label>
                      <label className="f">
                        <span>Stilling</span>
                        <input
                          type="text"
                          placeholder="Fx Client Manager"
                          value={state.meta.role}
                          onChange={(event) => setMeta('role', event.target.value)}
                        />
                      </label>
                      <label className="f">
                        <span>Virksomhed</span>
                        <input
                          type="text"
                          placeholder="Fx TV 2 Reklamesalg"
                          value={state.meta.comp}
                          onChange={(event) => setMeta('comp', event.target.value)}
                        />
                      </label>
                    </div>
                    <div className="grid3">
                      <label className="f">
                        <span>Ansættende leder</span>
                        <input
                          type="text"
                          placeholder="Navn"
                          value={state.meta.lead}
                          onChange={(event) => setMeta('lead', event.target.value)}
                        />
                      </label>
                      <label className="f">
                        <span>Samtale nr.</span>
                        <select
                          value={state.meta.round}
                          onChange={(event) => setMeta('round', event.target.value)}
                        >
                          <option>1. samtale</option>
                          <option>2. samtale</option>
                          <option>3. samtale</option>
                          <option>Efter testfeedback</option>
                        </select>
                      </label>
                      <label className="f">
                        <span>Dato</span>
                        <input
                          type="text"
                          value={state.meta.date}
                          onChange={(event) => setMeta('date', event.target.value)}
                        />
                      </label>
                    </div>

                    <p className="sub">Sagsnummer</p>
                    <div
                      style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}
                    >
                      <label className="f" style={{ margin: 0, flex: '0 1 280px' }}>
                        <span>Sagens nummer</span>
                        <input
                          type="text"
                          placeholder="Fx 01-ClientManager"
                          value={state.meta.case}
                          onChange={(event) => setMeta('case', event.target.value)}
                        />
                      </label>
                      <button
                        type="button"
                        className="btn ghost"
                        style={{ padding: '10px 16px' }}
                        onClick={generateCaseNumber}
                      >
                        Generér sagsnummer
                      </button>
                    </div>
                    <p
                      style={{
                        fontSize: 12.5,
                        color: 'var(--ink-45)',
                        margin: '8px 0 0',
                        maxWidth: '70ch',
                      }}
                    >
                      Udfyld stamdata først — nummeret præges af felterne: løbenummer + stilling, fx{' '}
                      <strong>01-ClientManager</strong>. Det står i rapportens hoved og bliver
                      filnavnet, når du gemmer sagen. Generér igen for at tælle op.
                    </p>

                    <p className="sub">Adfærdsprofil · arbejdsprofilen (graf 1)</p>
                    <div className="discset">
                      {FACTORS.map((factor) => (
                        <div className={`di di-${factor}`} key={factor}>
                          <header>
                            <i />
                            <b>
                              {factor} · {FACTOR_NAME[factor]}
                            </b>
                          </header>
                          <input
                            type="number"
                            min={0}
                            max={100}
                            value={state.work[factor]}
                            onChange={(event) =>
                              setState((current) => ({
                                ...current,
                                work: {
                                  ...current.work,
                                  [factor]: clamp(Number(event.target.value) || 0, 0, 100),
                                },
                              }))
                            }
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                <div className="pager noprint">
                  <button type="button" className="btn ghost" onClick={() => go(0)}>
                    Forrige side
                  </button>
                  <button type="button" className="btn" onClick={() => go(2)}>
                    Næste side
                  </button>
                </div>
                <div className="page-foot">
                  <span>MasterDISC · Jobmatch · Fortroligt</span>
                  <span className="pgnum">2</span>
                </div>
              </div>
            </section>

            {/* ============ STEP 2 ============ */}
            <section className={step === 2 ? 'step on' : 'step'} id="step2">
              <div className="page">
                <div className="page-head">
                  <b>MasterDISC - Jobmatch</b>
                </div>
                <div className="page-body">
                  <div className="card">
                    <p className="eyebrow">Trin 02</p>
                    <h2>Kravprofil for stillingen</h2>
                    <p className="lede">
                      Hvilken adfærd kalder jobbet på — ikke hvilken adfærd kandidaten har. Vælg et
                      udgangspunkt og juster. Det er her, din faglige vurdering af rollen sætter
                      målestokken for hele matchet.
                    </p>

                    <div className="chips">
                      {PRESETS.map((preset) => (
                        <button
                          type="button"
                          key={preset.id}
                          className={state.preset === preset.id ? 'chip on' : 'chip'}
                          onClick={() =>
                            setState((current) => ({
                              ...current,
                              preset: preset.id,
                              req: preset.req ? { ...preset.req } : current.req,
                            }))
                          }
                        >
                          {preset.name}
                        </button>
                      ))}
                    </div>
                    <button
                      type="button"
                      className="btn ghost small"
                      style={{ marginBottom: 20 }}
                      onClick={() => {
                        const suggestion = suggestFromText(jobFullText(state));
                        if (!suggestion) {
                          setSuggestOut(
                            'Der er ikke nok tekst at gå ud fra. Læg stillingsbeskrivelsen ind på trin 1, eller sæt kravprofilen manuelt.',
                          );
                          return;
                        }
                        setState((current) => ({
                          ...current,
                          req: suggestion.req,
                          preset: 'egen',
                        }));
                        setSuggestOut(
                          `Forslag ud fra ordvalget i opslaget (D:${suggestion.raw.D} · I:${suggestion.raw.I} · S:${suggestion.raw.S} · C:${suggestion.raw.C} signalord). Det er et udgangspunkt, ikke en facitliste — juster efter det, du ved om rollen.`,
                        );
                      }}
                    >
                      Foreslå kravprofil ud fra stillingsbeskrivelsen
                    </button>
                    <p style={{ fontSize: 13, color: 'var(--ink-70)', margin: '-10px 0 18px' }}>
                      {suggestOut}
                    </p>

                    <div>
                      {FACTORS.map((factor) => (
                        <div className="reqrow" key={factor}>
                          <div className="lab">
                            <i style={{ background: FACTOR_COLOR[factor] }} />
                            {factor} · {FACTOR_NAME[factor]}
                          </div>
                          <input
                            type="range"
                            min={0}
                            max={100}
                            value={state.req[factor]}
                            onChange={(event) =>
                              setState((current) => ({
                                ...current,
                                req: { ...current.req, [factor]: Number(event.target.value) },
                                preset: 'egen',
                              }))
                            }
                          />
                          <output>{state.req[factor]}</output>
                          <div
                            className="weights fwsel"
                            title={`Hvor vigtigt er det at ramme ${factor} i spændet?`}
                          >
                            {FACTOR_WEIGHTS.map((weight) => (
                              <button
                                type="button"
                                key={weight.w}
                                className={(state.fw[factor] || 1) === weight.w ? 'on' : undefined}
                                onClick={() =>
                                  setState((current) => ({
                                    ...current,
                                    fw: { ...current.fw, [factor]: weight.w },
                                  }))
                                }
                              >
                                {weight.label}
                              </button>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                    <p
                      style={{
                        fontSize: 12.5,
                        color: 'var(--ink-45)',
                        margin: '4px 0 0',
                        maxWidth: '70ch',
                      }}
                    >
                      Vægten til højre bestemmer, hvor hårdt det trækker ned at ramme uden for
                      spændet på netop den faktor. Er D-kravet vigtigst, sætter du D til{' '}
                      <strong>Høj</strong> — så koster en afvigelse på D mere end samme afvigelse på
                      C.
                    </p>

                    <p className="sub">Tolerance</p>
                    <div className="reqrow">
                      <div className="lab">Accepteret spænd</div>
                      <input
                        type="range"
                        min={5}
                        max={25}
                        value={state.tol}
                        onChange={(event) =>
                          setState((current) => ({ ...current, tol: Number(event.target.value) }))
                        }
                      />
                      <output>±{state.tol}</output>
                    </div>
                    <p
                      style={{
                        fontSize: 13,
                        color: 'var(--ink-70)',
                        margin: '2px 0 0',
                        maxWidth: '62ch',
                      }}
                    >
                      Inden for spændet regnes adfærden som et rent match. Stram op til ±8, hvis
                      rollen er snæver og kravene skarpe. Løsn til ±20, hvis du hellere vil ansætte
                      på potentiale end på præcision.
                    </p>
                  </div>
                </div>
                <div className="pager noprint">
                  <button type="button" className="btn ghost" onClick={() => go(1)}>
                    Forrige side
                  </button>
                  <button type="button" className="btn" onClick={() => go(3)}>
                    Næste side
                  </button>
                </div>
                <div className="page-foot">
                  <span>MasterDISC · Jobmatch · Fortroligt</span>
                  <span className="pgnum">3</span>
                </div>
              </div>
            </section>

            {/* ============ STEP 3 ============ */}
            <section className={step === 3 ? 'step on' : 'step'} id="step3">
              {pages.map((pageQuestions, pageIndex) => {
                const first = pageIndex === 0;
                const last = pageIndex === pages.length - 1;
                const offset = pageIndex * (wide ? QUESTIONS_PER_PAGE : questions.length);
                return (
                  <div className="page" key={pageIndex}>
                    <div className="page-head">
                      <b>MasterDISC - Jobmatch</b>
                    </div>
                    <div className="page-body">
                      <div className="card">
                        {first ? (
                          <>
                            <p className="eyebrow">Trin 03</p>
                            <h2>Din vurdering</h2>
                            <p className="lede">
                              De ting testen ikke måler. Svar på det, du faktisk har grundlag for at
                              svare på — sæt resten til &quot;ikke relevant&quot;, så tæller det
                              ikke med. Vægt hvert spørgsmål efter stillingen: <strong>Lav</strong>{' '}
                              tæller halvt, <strong>Normal</strong> fuldt, <strong>Høj</strong>{' '}
                              ekstra — og <strong>Kritisk</strong> tæller mest og udløser et
                              forbehold i rapporten, hvis scoren er 5 eller derunder, uanset
                              totalen.
                            </p>
                          </>
                        ) : (
                          <>
                            <p className="eyebrow">Trin 03 · fortsat</p>
                            <h2 style={{ fontSize: 22 }}>Din vurdering — fortsat</h2>
                          </>
                        )}
                        <div className="qhost">
                          {pageQuestions.map((question, index) =>
                            questionNode(question, offset + index),
                          )}
                          {last ? questionTail : null}
                        </div>
                      </div>
                    </div>
                    <div className="pager noprint" style={last ? undefined : { display: 'none' }}>
                      {last ? (
                        <>
                          <button type="button" className="btn ghost" onClick={() => go(2)}>
                            Forrige side
                          </button>
                          <button
                            type="button"
                            className="btn"
                            onClick={() => {
                              if (state.discRejected) {
                                go(1);
                                return;
                              }
                              buildReport();
                            }}
                          >
                            Næste side
                          </button>
                        </>
                      ) : null}
                    </div>
                    <div className="page-foot">
                      <span>MasterDISC · Jobmatch · Fortroligt</span>
                      <span className="pgnum">{4 + pageIndex}</span>
                    </div>
                  </div>
                );
              })}
            </section>

            {/* ============ STEP 4 ============ */}
            <section className={step === 4 ? 'step on' : 'step'} id="step4">
              <div className="toolbar">
                <button type="button" className="btn" onClick={saveToArchive} disabled={arkivBusy}>
                  {arkivLabel}
                </button>
                <button type="button" className="btn ghost" onClick={() => window.print()}>
                  Udskriv eller gem som PDF
                </button>
                <button type="button" className="btn ghost" onClick={() => go(3)}>
                  Forrige side
                </button>
                <button type="button" className="btn ghost" onClick={saveCaseToFile}>
                  {saveLabel}
                </button>
              </div>
              <p
                className="noprint"
                style={{
                  margin: '-8px 0 16px',
                  fontSize: 13,
                  fontWeight: 600,
                  minHeight: 19,
                  color: arkivStatus.color,
                }}
              >
                {arkivStatus.text}
              </p>
              {reportHtml ? (
                <div className="report paged" ref={reportRef} />
              ) : (
                <div className="report">
                  <div className="rep-head" style={{ padding: '22px 34px' }}>
                    <p className="eyebrow" style={{ margin: 0 }}>
                      MasterDISC - Jobmatch
                    </p>
                  </div>
                  <div className="md-gradient" />
                  <div className="empty">
                    Udfyld trin 1–3, og tryk &quot;Næste side&quot; eller &quot;Opdater
                    Jobmatch&quot; på vurderingssiden.
                  </div>
                  <div className="repfoot">
                    <span>MasterDISC · Jobmatch · Fortroligt</span>
                    <span className="pgnum">{reportPageNumber}</span>
                  </div>
                </div>
              )}
            </section>
          </main>
        </div>
      </div>
      <div className="printfoot">
        <span>MasterDISC · Jobmatch · Fortroligt</span>
        <span>Coachers</span>
      </div>
      <footer className="md-foot">
        <div className="shell footrow" style={{ paddingBottom: 18 }}>
          <span>MasterDISC · JobMatch · Fortroligt · Version 15.08.2026-26</span>
          <span className="pgnum">Coachers</span>
        </div>
      </footer>
    </>
  );
}
